# Generated by Django 2.1.4 on 2018-12-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monstro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='monstros/')),
                ('level', models.DecimalField(decimal_places=0, max_digits=3)),
                ('vida', models.DecimalField(decimal_places=0, max_digits=15)),
                ('mana', models.DecimalField(decimal_places=0, max_digits=15)),
                ('defesa', models.DecimalField(decimal_places=0, max_digits=10)),
                ('resistencia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ataque', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('alinhamento', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Monstro',
                'verbose_name_plural': 'Monstros',
            },
        ),
    ]
