# Generated by Django 2.1.4 on 2018-12-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='classes/')),
                ('descricao', models.TextField()),
                ('levelR', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ('levelR', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='habilidades/')),
                ('descricao', models.TextField()),
                ('levelR', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ('levelR', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='mapas/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='raças/')),
                ('descricao', models.TextField()),
                ('classes', models.ManyToManyField(to='core.Classe')),
                ('habilidades', models.ManyToManyField(to='core.Habilidade')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='monstro',
            options={'ordering': ('level', 'nome'), 'verbose_name': 'Monstro', 'verbose_name_plural': 'Monstros'},
        ),
        migrations.RemoveField(
            model_name='monstro',
            name='id',
        ),
        migrations.AlterField(
            model_name='monstro',
            name='nome',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mapa',
            name='monstros',
            field=models.ManyToManyField(to='core.Monstro'),
        ),
        migrations.AddField(
            model_name='classe',
            name='habilidades',
            field=models.ManyToManyField(to='core.Habilidade'),
        ),
        migrations.AddField(
            model_name='monstro',
            name='habilidades',
            field=models.ManyToManyField(to='core.Habilidade'),
        ),
    ]
