# Generated by Django 2.1.4 on 2018-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181228_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, to='core.Habilidade'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='monstros',
            field=models.ManyToManyField(blank=True, null=True, to='core.Monstro'),
        ),
        migrations.AlterField(
            model_name='monstro',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, to='core.Habilidade'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='core.Classe'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='habilidades',
            field=models.ManyToManyField(blank=True, null=True, to='core.Habilidade'),
        ),
    ]
