# Generated by Django 2.1.4 on 2018-12-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='core.Habilidade'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='monstros',
            field=models.ManyToManyField(blank=True, to='core.Monstro'),
        ),
        migrations.AlterField(
            model_name='monstro',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Classe'),
        ),
        migrations.AlterField(
            model_name='monstro',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='core.Habilidade'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='classes',
            field=models.ManyToManyField(blank=True, to='core.Classe'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='core.Habilidade'),
        ),
    ]
