# Generated by Django 2.1.4 on 2018-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181228_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='classes/')),
                ('descricao', models.TextField()),
                ('levelR', models.DecimalField(decimal_places=0, max_digits=3)),
                ('vida', models.DecimalField(decimal_places=0, max_digits=15)),
                ('mana', models.DecimalField(decimal_places=0, max_digits=15)),
                ('defesa', models.DecimalField(decimal_places=0, max_digits=10)),
                ('resistencia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ataque', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('habilidades', models.ManyToManyField(blank=True, to='core.Habilidade')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ('levelR', 'nome'),
            },
        ),
        migrations.AddField(
            model_name='monstro',
            name='ouro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monstro',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.Item'),
        ),
    ]
