# Generated by Django 2.1.4 on 2018-12-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181228_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('levelR', 'nome'), 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
