# Generated by Django 2.1.4 on 2018-12-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181228_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classes',
            field=models.ManyToManyField(blank=True, to='core.Classe'),
        ),
    ]
